require 'find'
require 'ftools'

require 'eventmachine'
require 'evma_xmlpushparser'
require 'xmpp4r'
require 'xmpp4r/roster'
require 'xmpp4r/version'
require 'xmpp4r/dataforms'
require 'xmpp4r/command/iq/command'

require 'agent_xmpp/config'
require 'agent_xmpp/app'
require 'agent_xmpp/client'
require 'agent_xmpp/utils'
require 'agent_xmpp/patches'
