require 'agent_xmpp/app/boot'
require 'agent_xmpp/app/controller'
require 'agent_xmpp/app/format'
require 'agent_xmpp/app/map'
require 'agent_xmpp/app/routes'
require 'agent_xmpp/app/view'
require 'agent_xmpp/app/chat_message_body_controller'
