require 'agent_xmpp/client/messages/roster_messages'
require 'agent_xmpp/client/messages/service_discovery_messages'
require 'agent_xmpp/client/messages/presence_messages'
require 'agent_xmpp/client/messages/session_messages'
require 'agent_xmpp/client/messages/application_messages'

require 'agent_xmpp/client/parser'
require 'agent_xmpp/client/response'
require 'agent_xmpp/client/message_pipe'
require 'agent_xmpp/client/connection'
require 'agent_xmpp/client/client'
