require 'agent_xmpp/models/table_definitions'
require 'agent_xmpp/models/contact_model'
require 'agent_xmpp/models/roster_model'
require 'agent_xmpp/models/services_model'
require 'agent_xmpp/models/publish_model'
