require 'agent_xmpp/models/table_definitions'
require 'agent_xmpp/models/contact'
require 'agent_xmpp/models/roster'
require 'agent_xmpp/models/service'
require 'agent_xmpp/models/publication'
require 'agent_xmpp/models/subscription'
require 'agent_xmpp/models/message'
